#!/bin/bash
DATE_STR=$(TZ='Europe/Paris' date +'%d/%m/%Y à %H:%M')
if sed --version >/dev/null 2>&1; then
  # GNU sed
  sed -i -E "s|Dernière mise à jour : [0-9]{2}/[0-9]{2}/[0-9]{4} à [0-9]{2}:[0-9]{2}|Dernière mise à jour : $DATE_STR|" index.html
else
  # BSD sed (macOS)
  sed -i '' -E "s|Dernière mise à jour : [0-9]{2}/[0-9]{2}/[0-9]{4} à [0-9]{2}:[0-9]{2}|Dernière mise à jour : $DATE_STR|" index.html
fi
git add index.html
